### ISSUE TITLE
Changes to APIs, internal workings and meta data

### ISSUE THREAD

**Issue by waternumbers** [waternumbers/ukg#6]
Changes to the data returned when requesting information for a single station
- [ ] Provide copyright info in api response
- [ ] Provide forecast data so it "Joins up" with observed data (no gap in plots)

Changes to data returned when requesting all stations
- [ ] Minimise data returned
- [ ] Provide copyright info in api response

Changes to internals
- [ ] Correctly handle forecast objects as blobs for flexibility
- [ ] Improve speed to data ingestion (one file/table per series to simplify indexing?)
- [ ] async database calls in api

Met data
- [ ] Add wmts layer for met forecast

nginx setup
- [ ] Ensure compression is on
- [ ] Turn on caching
